// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: api/proto/uk_service.proto

package ukpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UkService_CreateUser_FullMethodName           = "/ru.rabtra.api.UkService/CreateUser"
	UkService_GetUserMe_FullMethodName            = "/ru.rabtra.api.UkService/GetUserMe"
	UkService_CreateHouse_FullMethodName          = "/ru.rabtra.api.UkService/CreateHouse"
	UkService_GetMyHouses_FullMethodName          = "/ru.rabtra.api.UkService/GetMyHouses"
	UkService_SearchHouseByAddress_FullMethodName = "/ru.rabtra.api.UkService/SearchHouseByAddress"
	UkService_GetFlatsByHouse_FullMethodName      = "/ru.rabtra.api.UkService/GetFlatsByHouse"
	UkService_CreateMyFlat_FullMethodName         = "/ru.rabtra.api.UkService/CreateMyFlat"
	UkService_GetMyFlats_FullMethodName           = "/ru.rabtra.api.UkService/GetMyFlats"
	UkService_CreateServiceRequest_FullMethodName = "/ru.rabtra.api.UkService/CreateServiceRequest"
	UkService_GetMyRequests_FullMethodName        = "/ru.rabtra.api.UkService/GetMyRequests"
	UkService_GetCompanyRequests_FullMethodName   = "/ru.rabtra.api.UkService/GetCompanyRequests"
	UkService_UpdateRequestStatus_FullMethodName  = "/ru.rabtra.api.UkService/UpdateRequestStatus"
)

// UkServiceClient is the client API for UkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UkServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequestProto, opts ...grpc.CallOption) (*UserResponseProto, error)
	GetUserMe(ctx context.Context, in *GetUserMeRequestProto, opts ...grpc.CallOption) (*UserResponseProto, error)
	CreateHouse(ctx context.Context, in *CreateHouseRequestProto, opts ...grpc.CallOption) (*HouseResponseProto, error)
	GetMyHouses(ctx context.Context, in *GetMyHousesRequestProto, opts ...grpc.CallOption) (*HouseListResponseProto, error)
	SearchHouseByAddress(ctx context.Context, in *SearchHouseByAddressRequestProto, opts ...grpc.CallOption) (*HouseResponseProto, error)
	GetFlatsByHouse(ctx context.Context, in *GetFlatsRequestProto, opts ...grpc.CallOption) (*FlatListResponseProto, error)
	CreateMyFlat(ctx context.Context, in *CreateMyFlatRequestProto, opts ...grpc.CallOption) (*UserFlatResponseProto, error)
	GetMyFlats(ctx context.Context, in *GetMyFlatsRequestProto, opts ...grpc.CallOption) (*UserFlatListResponseProto, error)
	CreateServiceRequest(ctx context.Context, in *CreateServiceRequestProto, opts ...grpc.CallOption) (*ServiceRequestResponseProto, error)
	GetMyRequests(ctx context.Context, in *GetMyServiceRequestsProto, opts ...grpc.CallOption) (*ServiceRequestListResponseProto, error)
	GetCompanyRequests(ctx context.Context, in *GetCompanyServiceRequestsProto, opts ...grpc.CallOption) (*ServiceRequestListResponseProto, error)
	UpdateRequestStatus(ctx context.Context, in *UpdateServiceRequestStatusProto, opts ...grpc.CallOption) (*ServiceRequestResponseProto, error)
}

type ukServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUkServiceClient(cc grpc.ClientConnInterface) UkServiceClient {
	return &ukServiceClient{cc}
}

func (c *ukServiceClient) CreateUser(ctx context.Context, in *CreateUserRequestProto, opts ...grpc.CallOption) (*UserResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponseProto)
	err := c.cc.Invoke(ctx, UkService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetUserMe(ctx context.Context, in *GetUserMeRequestProto, opts ...grpc.CallOption) (*UserResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetUserMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) CreateHouse(ctx context.Context, in *CreateHouseRequestProto, opts ...grpc.CallOption) (*HouseResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HouseResponseProto)
	err := c.cc.Invoke(ctx, UkService_CreateHouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetMyHouses(ctx context.Context, in *GetMyHousesRequestProto, opts ...grpc.CallOption) (*HouseListResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HouseListResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetMyHouses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) SearchHouseByAddress(ctx context.Context, in *SearchHouseByAddressRequestProto, opts ...grpc.CallOption) (*HouseResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HouseResponseProto)
	err := c.cc.Invoke(ctx, UkService_SearchHouseByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetFlatsByHouse(ctx context.Context, in *GetFlatsRequestProto, opts ...grpc.CallOption) (*FlatListResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlatListResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetFlatsByHouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) CreateMyFlat(ctx context.Context, in *CreateMyFlatRequestProto, opts ...grpc.CallOption) (*UserFlatResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFlatResponseProto)
	err := c.cc.Invoke(ctx, UkService_CreateMyFlat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetMyFlats(ctx context.Context, in *GetMyFlatsRequestProto, opts ...grpc.CallOption) (*UserFlatListResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFlatListResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetMyFlats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) CreateServiceRequest(ctx context.Context, in *CreateServiceRequestProto, opts ...grpc.CallOption) (*ServiceRequestResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequestResponseProto)
	err := c.cc.Invoke(ctx, UkService_CreateServiceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetMyRequests(ctx context.Context, in *GetMyServiceRequestsProto, opts ...grpc.CallOption) (*ServiceRequestListResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequestListResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetMyRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) GetCompanyRequests(ctx context.Context, in *GetCompanyServiceRequestsProto, opts ...grpc.CallOption) (*ServiceRequestListResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequestListResponseProto)
	err := c.cc.Invoke(ctx, UkService_GetCompanyRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ukServiceClient) UpdateRequestStatus(ctx context.Context, in *UpdateServiceRequestStatusProto, opts ...grpc.CallOption) (*ServiceRequestResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequestResponseProto)
	err := c.cc.Invoke(ctx, UkService_UpdateRequestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UkServiceServer is the server API for UkService service.
// All implementations must embed UnimplementedUkServiceServer
// for forward compatibility.
type UkServiceServer interface {
	CreateUser(context.Context, *CreateUserRequestProto) (*UserResponseProto, error)
	GetUserMe(context.Context, *GetUserMeRequestProto) (*UserResponseProto, error)
	CreateHouse(context.Context, *CreateHouseRequestProto) (*HouseResponseProto, error)
	GetMyHouses(context.Context, *GetMyHousesRequestProto) (*HouseListResponseProto, error)
	SearchHouseByAddress(context.Context, *SearchHouseByAddressRequestProto) (*HouseResponseProto, error)
	GetFlatsByHouse(context.Context, *GetFlatsRequestProto) (*FlatListResponseProto, error)
	CreateMyFlat(context.Context, *CreateMyFlatRequestProto) (*UserFlatResponseProto, error)
	GetMyFlats(context.Context, *GetMyFlatsRequestProto) (*UserFlatListResponseProto, error)
	CreateServiceRequest(context.Context, *CreateServiceRequestProto) (*ServiceRequestResponseProto, error)
	GetMyRequests(context.Context, *GetMyServiceRequestsProto) (*ServiceRequestListResponseProto, error)
	GetCompanyRequests(context.Context, *GetCompanyServiceRequestsProto) (*ServiceRequestListResponseProto, error)
	UpdateRequestStatus(context.Context, *UpdateServiceRequestStatusProto) (*ServiceRequestResponseProto, error)
	mustEmbedUnimplementedUkServiceServer()
}

// UnimplementedUkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUkServiceServer struct{}

func (UnimplementedUkServiceServer) CreateUser(context.Context, *CreateUserRequestProto) (*UserResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUkServiceServer) GetUserMe(context.Context, *GetUserMeRequestProto) (*UserResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMe not implemented")
}
func (UnimplementedUkServiceServer) CreateHouse(context.Context, *CreateHouseRequestProto) (*HouseResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHouse not implemented")
}
func (UnimplementedUkServiceServer) GetMyHouses(context.Context, *GetMyHousesRequestProto) (*HouseListResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyHouses not implemented")
}
func (UnimplementedUkServiceServer) SearchHouseByAddress(context.Context, *SearchHouseByAddressRequestProto) (*HouseResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchHouseByAddress not implemented")
}
func (UnimplementedUkServiceServer) GetFlatsByHouse(context.Context, *GetFlatsRequestProto) (*FlatListResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlatsByHouse not implemented")
}
func (UnimplementedUkServiceServer) CreateMyFlat(context.Context, *CreateMyFlatRequestProto) (*UserFlatResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMyFlat not implemented")
}
func (UnimplementedUkServiceServer) GetMyFlats(context.Context, *GetMyFlatsRequestProto) (*UserFlatListResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFlats not implemented")
}
func (UnimplementedUkServiceServer) CreateServiceRequest(context.Context, *CreateServiceRequestProto) (*ServiceRequestResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceRequest not implemented")
}
func (UnimplementedUkServiceServer) GetMyRequests(context.Context, *GetMyServiceRequestsProto) (*ServiceRequestListResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyRequests not implemented")
}
func (UnimplementedUkServiceServer) GetCompanyRequests(context.Context, *GetCompanyServiceRequestsProto) (*ServiceRequestListResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanyRequests not implemented")
}
func (UnimplementedUkServiceServer) UpdateRequestStatus(context.Context, *UpdateServiceRequestStatusProto) (*ServiceRequestResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRequestStatus not implemented")
}
func (UnimplementedUkServiceServer) mustEmbedUnimplementedUkServiceServer() {}
func (UnimplementedUkServiceServer) testEmbeddedByValue()                   {}

// UnsafeUkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UkServiceServer will
// result in compilation errors.
type UnsafeUkServiceServer interface {
	mustEmbedUnimplementedUkServiceServer()
}

func RegisterUkServiceServer(s grpc.ServiceRegistrar, srv UkServiceServer) {
	// If the following call panics, it indicates UnimplementedUkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UkService_ServiceDesc, srv)
}

func _UkService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).CreateUser(ctx, req.(*CreateUserRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetUserMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMeRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetUserMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetUserMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetUserMe(ctx, req.(*GetUserMeRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_CreateHouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).CreateHouse(ctx, req.(*CreateHouseRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetMyHouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyHousesRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetMyHouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetMyHouses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetMyHouses(ctx, req.(*GetMyHousesRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_SearchHouseByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHouseByAddressRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).SearchHouseByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_SearchHouseByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).SearchHouseByAddress(ctx, req.(*SearchHouseByAddressRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetFlatsByHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlatsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetFlatsByHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetFlatsByHouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetFlatsByHouse(ctx, req.(*GetFlatsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_CreateMyFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMyFlatRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).CreateMyFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_CreateMyFlat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).CreateMyFlat(ctx, req.(*CreateMyFlatRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetMyFlats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFlatsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetMyFlats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetMyFlats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetMyFlats(ctx, req.(*GetMyFlatsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_CreateServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).CreateServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_CreateServiceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).CreateServiceRequest(ctx, req.(*CreateServiceRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetMyRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyServiceRequestsProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetMyRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetMyRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetMyRequests(ctx, req.(*GetMyServiceRequestsProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_GetCompanyRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyServiceRequestsProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).GetCompanyRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_GetCompanyRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).GetCompanyRequests(ctx, req.(*GetCompanyServiceRequestsProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _UkService_UpdateRequestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequestStatusProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UkServiceServer).UpdateRequestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UkService_UpdateRequestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UkServiceServer).UpdateRequestStatus(ctx, req.(*UpdateServiceRequestStatusProto))
	}
	return interceptor(ctx, in, info, handler)
}

// UkService_ServiceDesc is the grpc.ServiceDesc for UkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ru.rabtra.api.UkService",
	HandlerType: (*UkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UkService_CreateUser_Handler,
		},
		{
			MethodName: "GetUserMe",
			Handler:    _UkService_GetUserMe_Handler,
		},
		{
			MethodName: "CreateHouse",
			Handler:    _UkService_CreateHouse_Handler,
		},
		{
			MethodName: "GetMyHouses",
			Handler:    _UkService_GetMyHouses_Handler,
		},
		{
			MethodName: "SearchHouseByAddress",
			Handler:    _UkService_SearchHouseByAddress_Handler,
		},
		{
			MethodName: "GetFlatsByHouse",
			Handler:    _UkService_GetFlatsByHouse_Handler,
		},
		{
			MethodName: "CreateMyFlat",
			Handler:    _UkService_CreateMyFlat_Handler,
		},
		{
			MethodName: "GetMyFlats",
			Handler:    _UkService_GetMyFlats_Handler,
		},
		{
			MethodName: "CreateServiceRequest",
			Handler:    _UkService_CreateServiceRequest_Handler,
		},
		{
			MethodName: "GetMyRequests",
			Handler:    _UkService_GetMyRequests_Handler,
		},
		{
			MethodName: "GetCompanyRequests",
			Handler:    _UkService_GetCompanyRequests_Handler,
		},
		{
			MethodName: "UpdateRequestStatus",
			Handler:    _UkService_UpdateRequestStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/uk_service.proto",
}
