// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/proto/uk_service.proto

package ukpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleProto int32

const (
	RoleProto_ROLE_UNSPECIFIED RoleProto = 0
	RoleProto_ROLE_USER        RoleProto = 1
	RoleProto_ROLE_COMPANY     RoleProto = 2
)

// Enum value maps for RoleProto.
var (
	RoleProto_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_COMPANY",
	}
	RoleProto_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_COMPANY":     2,
	}
)

func (x RoleProto) Enum() *RoleProto {
	p := new(RoleProto)
	*p = x
	return p
}

func (x RoleProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleProto) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_uk_service_proto_enumTypes[0].Descriptor()
}

func (RoleProto) Type() protoreflect.EnumType {
	return &file_api_proto_uk_service_proto_enumTypes[0]
}

func (x RoleProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleProto.Descriptor instead.
func (RoleProto) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{0}
}

type RequestTypeProto int32

const (
	RequestTypeProto_TYPE_UNSPECIFIED     RequestTypeProto = 0
	RequestTypeProto_TYPE_DIRTY_ENTRANCE  RequestTypeProto = 1
	RequestTypeProto_TYPE_ELEVATOR_BROKEN RequestTypeProto = 2
	RequestTypeProto_TYPE_NOISY_NEIGHBORS RequestTypeProto = 3
	RequestTypeProto_TYPE_PLUMBING        RequestTypeProto = 4
	RequestTypeProto_TYPE_ELECTRICITY     RequestTypeProto = 5
	RequestTypeProto_TYPE_HEATING         RequestTypeProto = 6
	RequestTypeProto_TYPE_INTERCOM        RequestTypeProto = 7
	RequestTypeProto_TYPE_PARKING         RequestTypeProto = 8
	RequestTypeProto_TYPE_OTHER           RequestTypeProto = 9
)

// Enum value maps for RequestTypeProto.
var (
	RequestTypeProto_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_DIRTY_ENTRANCE",
		2: "TYPE_ELEVATOR_BROKEN",
		3: "TYPE_NOISY_NEIGHBORS",
		4: "TYPE_PLUMBING",
		5: "TYPE_ELECTRICITY",
		6: "TYPE_HEATING",
		7: "TYPE_INTERCOM",
		8: "TYPE_PARKING",
		9: "TYPE_OTHER",
	}
	RequestTypeProto_value = map[string]int32{
		"TYPE_UNSPECIFIED":     0,
		"TYPE_DIRTY_ENTRANCE":  1,
		"TYPE_ELEVATOR_BROKEN": 2,
		"TYPE_NOISY_NEIGHBORS": 3,
		"TYPE_PLUMBING":        4,
		"TYPE_ELECTRICITY":     5,
		"TYPE_HEATING":         6,
		"TYPE_INTERCOM":        7,
		"TYPE_PARKING":         8,
		"TYPE_OTHER":           9,
	}
)

func (x RequestTypeProto) Enum() *RequestTypeProto {
	p := new(RequestTypeProto)
	*p = x
	return p
}

func (x RequestTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_uk_service_proto_enumTypes[1].Descriptor()
}

func (RequestTypeProto) Type() protoreflect.EnumType {
	return &file_api_proto_uk_service_proto_enumTypes[1]
}

func (x RequestTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestTypeProto.Descriptor instead.
func (RequestTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{1}
}

type RequestStatusProto int32

const (
	RequestStatusProto_STATUS_UNSPECIFIED RequestStatusProto = 0
	RequestStatusProto_STATUS_NEW         RequestStatusProto = 1
	RequestStatusProto_STATUS_IN_PROGRESS RequestStatusProto = 2
	RequestStatusProto_STATUS_DONE        RequestStatusProto = 3
)

// Enum value maps for RequestStatusProto.
var (
	RequestStatusProto_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_NEW",
		2: "STATUS_IN_PROGRESS",
		3: "STATUS_DONE",
	}
	RequestStatusProto_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_NEW":         1,
		"STATUS_IN_PROGRESS": 2,
		"STATUS_DONE":        3,
	}
)

func (x RequestStatusProto) Enum() *RequestStatusProto {
	p := new(RequestStatusProto)
	*p = x
	return p
}

func (x RequestStatusProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatusProto) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_uk_service_proto_enumTypes[2].Descriptor()
}

func (RequestStatusProto) Type() protoreflect.EnumType {
	return &file_api_proto_uk_service_proto_enumTypes[2]
}

func (x RequestStatusProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatusProto.Descriptor instead.
func (RequestStatusProto) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{2}
}

type CreateUserRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Role          RoleProto              `protobuf:"varint,6,opt,name=role,proto3,enum=ru.rabtra.api.RoleProto" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequestProto) Reset() {
	*x = CreateUserRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequestProto) ProtoMessage() {}

func (x *CreateUserRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequestProto.ProtoReflect.Descriptor instead.
func (*CreateUserRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequestProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequestProto) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CreateUserRequestProto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequestProto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequestProto) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequestProto) GetRole() RoleProto {
	if x != nil {
		return x.Role
	}
	return RoleProto_ROLE_UNSPECIFIED
}

type GetUserMeRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMeRequestProto) Reset() {
	*x = GetUserMeRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMeRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMeRequestProto) ProtoMessage() {}

func (x *GetUserMeRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMeRequestProto.ProtoReflect.Descriptor instead.
func (*GetUserMeRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserMeRequestProto) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type UserResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Role          RoleProto              `protobuf:"varint,6,opt,name=role,proto3,enum=ru.rabtra.api.RoleProto" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponseProto) Reset() {
	*x = UserResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponseProto) ProtoMessage() {}

func (x *UserResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponseProto.ProtoReflect.Descriptor instead.
func (*UserResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponseProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponseProto) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserResponseProto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserResponseProto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserResponseProto) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserResponseProto) GetRole() RoleProto {
	if x != nil {
		return x.Role
	}
	return RoleProto_ROLE_UNSPECIFIED
}

func (x *UserResponseProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateHouseRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,4,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseRequestProto) Reset() {
	*x = CreateHouseRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseRequestProto) ProtoMessage() {}

func (x *CreateHouseRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseRequestProto.ProtoReflect.Descriptor instead.
func (*CreateHouseRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHouseRequestProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *CreateHouseRequestProto) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateHouseRequestProto) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateHouseRequestProto) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

type GetMyHousesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyHousesRequestProto) Reset() {
	*x = GetMyHousesRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyHousesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyHousesRequestProto) ProtoMessage() {}

func (x *GetMyHousesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyHousesRequestProto.ProtoReflect.Descriptor instead.
func (*GetMyHousesRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyHousesRequestProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

type SearchHouseByAddressRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,3,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHouseByAddressRequestProto) Reset() {
	*x = SearchHouseByAddressRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHouseByAddressRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHouseByAddressRequestProto) ProtoMessage() {}

func (x *SearchHouseByAddressRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHouseByAddressRequestProto.ProtoReflect.Descriptor instead.
func (*SearchHouseByAddressRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHouseByAddressRequestProto) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchHouseByAddressRequestProto) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *SearchHouseByAddressRequestProto) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

type HouseResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     int64                  `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,5,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseResponseProto) Reset() {
	*x = HouseResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseResponseProto) ProtoMessage() {}

func (x *HouseResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseResponseProto.ProtoReflect.Descriptor instead.
func (*HouseResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{6}
}

func (x *HouseResponseProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseResponseProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *HouseResponseProto) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *HouseResponseProto) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *HouseResponseProto) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

type HouseListResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Houses        []*HouseResponseProto  `protobuf:"bytes,1,rep,name=houses,proto3" json:"houses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseListResponseProto) Reset() {
	*x = HouseListResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseListResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseListResponseProto) ProtoMessage() {}

func (x *HouseListResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseListResponseProto.ProtoReflect.Descriptor instead.
func (*HouseListResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{7}
}

func (x *HouseListResponseProto) GetHouses() []*HouseResponseProto {
	if x != nil {
		return x.Houses
	}
	return nil
}

type GetFlatsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       int64                  `protobuf:"varint,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlatsRequestProto) Reset() {
	*x = GetFlatsRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlatsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlatsRequestProto) ProtoMessage() {}

func (x *GetFlatsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlatsRequestProto.ProtoReflect.Descriptor instead.
func (*GetFlatsRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetFlatsRequestProto) GetHouseId() int64 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

type FlatResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,4,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	FlatNumber    int32                  `protobuf:"varint,5,opt,name=flat_number,json=flatNumber,proto3" json:"flat_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatResponseProto) Reset() {
	*x = FlatResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatResponseProto) ProtoMessage() {}

func (x *FlatResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatResponseProto.ProtoReflect.Descriptor instead.
func (*FlatResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{9}
}

func (x *FlatResponseProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlatResponseProto) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *FlatResponseProto) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *FlatResponseProto) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *FlatResponseProto) GetFlatNumber() int32 {
	if x != nil {
		return x.FlatNumber
	}
	return 0
}

type FlatListResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flats         []*FlatResponseProto   `protobuf:"bytes,1,rep,name=flats,proto3" json:"flats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatListResponseProto) Reset() {
	*x = FlatListResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatListResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatListResponseProto) ProtoMessage() {}

func (x *FlatListResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatListResponseProto.ProtoReflect.Descriptor instead.
func (*FlatListResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{10}
}

func (x *FlatListResponseProto) GetFlats() []*FlatResponseProto {
	if x != nil {
		return x.Flats
	}
	return nil
}

type CreateMyFlatRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	HouseId       int64                  `protobuf:"varint,2,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	FlatNumber    int32                  `protobuf:"varint,3,opt,name=flat_number,json=flatNumber,proto3" json:"flat_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMyFlatRequestProto) Reset() {
	*x = CreateMyFlatRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMyFlatRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMyFlatRequestProto) ProtoMessage() {}

func (x *CreateMyFlatRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMyFlatRequestProto.ProtoReflect.Descriptor instead.
func (*CreateMyFlatRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMyFlatRequestProto) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateMyFlatRequestProto) GetHouseId() int64 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *CreateMyFlatRequestProto) GetFlatNumber() int32 {
	if x != nil {
		return x.FlatNumber
	}
	return 0
}

type GetMyFlatsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFlatsRequestProto) Reset() {
	*x = GetMyFlatsRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFlatsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFlatsRequestProto) ProtoMessage() {}

func (x *GetMyFlatsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFlatsRequestProto.ProtoReflect.Descriptor instead.
func (*GetMyFlatsRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyFlatsRequestProto) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type UserFlatResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFlatId    int64                  `protobuf:"varint,1,opt,name=user_flat_id,json=userFlatId,proto3" json:"user_flat_id,omitempty"`
	Flat          *FlatResponseProto     `protobuf:"bytes,2,opt,name=flat,proto3" json:"flat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFlatResponseProto) Reset() {
	*x = UserFlatResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFlatResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFlatResponseProto) ProtoMessage() {}

func (x *UserFlatResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFlatResponseProto.ProtoReflect.Descriptor instead.
func (*UserFlatResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{13}
}

func (x *UserFlatResponseProto) GetUserFlatId() int64 {
	if x != nil {
		return x.UserFlatId
	}
	return 0
}

func (x *UserFlatResponseProto) GetFlat() *FlatResponseProto {
	if x != nil {
		return x.Flat
	}
	return nil
}

type UserFlatListResponseProto struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	MyFlats       []*UserFlatResponseProto `protobuf:"bytes,1,rep,name=my_flats,json=myFlats,proto3" json:"my_flats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFlatListResponseProto) Reset() {
	*x = UserFlatListResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFlatListResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFlatListResponseProto) ProtoMessage() {}

func (x *UserFlatListResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFlatListResponseProto.ProtoReflect.Descriptor instead.
func (*UserFlatListResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{14}
}

func (x *UserFlatListResponseProto) GetMyFlats() []*UserFlatResponseProto {
	if x != nil {
		return x.MyFlats
	}
	return nil
}

type CreateServiceRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	UserFlatsId   int64                  `protobuf:"varint,2,opt,name=user_flats_id,json=userFlatsId,proto3" json:"user_flats_id,omitempty"`
	Type          RequestTypeProto       `protobuf:"varint,3,opt,name=type,proto3,enum=ru.rabtra.api.RequestTypeProto" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequestProto) Reset() {
	*x = CreateServiceRequestProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequestProto) ProtoMessage() {}

func (x *CreateServiceRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequestProto.ProtoReflect.Descriptor instead.
func (*CreateServiceRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateServiceRequestProto) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateServiceRequestProto) GetUserFlatsId() int64 {
	if x != nil {
		return x.UserFlatsId
	}
	return 0
}

func (x *CreateServiceRequestProto) GetType() RequestTypeProto {
	if x != nil {
		return x.Type
	}
	return RequestTypeProto_TYPE_UNSPECIFIED
}

func (x *CreateServiceRequestProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateServiceRequestProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetMyServiceRequestsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyServiceRequestsProto) Reset() {
	*x = GetMyServiceRequestsProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyServiceRequestsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyServiceRequestsProto) ProtoMessage() {}

func (x *GetMyServiceRequestsProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyServiceRequestsProto.ProtoReflect.Descriptor instead.
func (*GetMyServiceRequestsProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetMyServiceRequestsProto) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type GetCompanyServiceRequestsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Status        *RequestStatusProto    `protobuf:"varint,2,opt,name=status,proto3,enum=ru.rabtra.api.RequestStatusProto,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyServiceRequestsProto) Reset() {
	*x = GetCompanyServiceRequestsProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyServiceRequestsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyServiceRequestsProto) ProtoMessage() {}

func (x *GetCompanyServiceRequestsProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyServiceRequestsProto.ProtoReflect.Descriptor instead.
func (*GetCompanyServiceRequestsProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetCompanyServiceRequestsProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetCompanyServiceRequestsProto) GetStatus() RequestStatusProto {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return RequestStatusProto_STATUS_UNSPECIFIED
}

type UpdateServiceRequestStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        RequestStatusProto     `protobuf:"varint,3,opt,name=status,proto3,enum=ru.rabtra.api.RequestStatusProto" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequestStatusProto) Reset() {
	*x = UpdateServiceRequestStatusProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequestStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequestStatusProto) ProtoMessage() {}

func (x *UpdateServiceRequestStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequestStatusProto.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequestStatusProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateServiceRequestStatusProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UpdateServiceRequestStatusProto) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *UpdateServiceRequestStatusProto) GetStatus() RequestStatusProto {
	if x != nil {
		return x.Status
	}
	return RequestStatusProto_STATUS_UNSPECIFIED
}

type ServiceRequestResponseProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserFlatsId        int64                  `protobuf:"varint,2,opt,name=user_flats_id,json=userFlatsId,proto3" json:"user_flats_id,omitempty"`
	CompanyId          int64                  `protobuf:"varint,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Type               RequestTypeProto       `protobuf:"varint,4,opt,name=type,proto3,enum=ru.rabtra.api.RequestTypeProto" json:"type,omitempty"`
	Title              string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description        string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status             RequestStatusProto     `protobuf:"varint,7,opt,name=status,proto3,enum=ru.rabtra.api.RequestStatusProto" json:"status,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	City               string                 `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Street             string                 `protobuf:"bytes,11,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber        string                 `protobuf:"bytes,12,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	FlatNumber         int32                  `protobuf:"varint,13,opt,name=flat_number,json=flatNumber,proto3" json:"flat_number,omitempty"`
	ApplicantFirstName string                 `protobuf:"bytes,14,opt,name=applicant_first_name,json=applicantFirstName,proto3" json:"applicant_first_name,omitempty"`
	ApplicantLastName  string                 `protobuf:"bytes,15,opt,name=applicant_last_name,json=applicantLastName,proto3" json:"applicant_last_name,omitempty"`
	ApplicantPhone     string                 `protobuf:"bytes,16,opt,name=applicant_phone,json=applicantPhone,proto3" json:"applicant_phone,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceRequestResponseProto) Reset() {
	*x = ServiceRequestResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequestResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequestResponseProto) ProtoMessage() {}

func (x *ServiceRequestResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequestResponseProto.ProtoReflect.Descriptor instead.
func (*ServiceRequestResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceRequestResponseProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceRequestResponseProto) GetUserFlatsId() int64 {
	if x != nil {
		return x.UserFlatsId
	}
	return 0
}

func (x *ServiceRequestResponseProto) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *ServiceRequestResponseProto) GetType() RequestTypeProto {
	if x != nil {
		return x.Type
	}
	return RequestTypeProto_TYPE_UNSPECIFIED
}

func (x *ServiceRequestResponseProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetStatus() RequestStatusProto {
	if x != nil {
		return x.Status
	}
	return RequestStatusProto_STATUS_UNSPECIFIED
}

func (x *ServiceRequestResponseProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceRequestResponseProto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServiceRequestResponseProto) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetFlatNumber() int32 {
	if x != nil {
		return x.FlatNumber
	}
	return 0
}

func (x *ServiceRequestResponseProto) GetApplicantFirstName() string {
	if x != nil {
		return x.ApplicantFirstName
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetApplicantLastName() string {
	if x != nil {
		return x.ApplicantLastName
	}
	return ""
}

func (x *ServiceRequestResponseProto) GetApplicantPhone() string {
	if x != nil {
		return x.ApplicantPhone
	}
	return ""
}

type ServiceRequestListResponseProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Requests      []*ServiceRequestResponseProto `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequestListResponseProto) Reset() {
	*x = ServiceRequestListResponseProto{}
	mi := &file_api_proto_uk_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequestListResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequestListResponseProto) ProtoMessage() {}

func (x *ServiceRequestListResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_uk_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequestListResponseProto.ProtoReflect.Descriptor instead.
func (*ServiceRequestListResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_uk_service_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceRequestListResponseProto) GetRequests() []*ServiceRequestResponseProto {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_api_proto_uk_service_proto protoreflect.FileDescriptor

const file_api_proto_uk_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/uk_service.proto\x12\rru.rabtra.api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\x16CreateUserRequestProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12,\n" +
	"\x04role\x18\x06 \x01(\x0e2\x18.ru.rabtra.api.RoleProtoR\x04role\":\n" +
	"\x15GetUserMeRequestProto\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\"\x84\x02\n" +
	"\x11UserResponseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12,\n" +
	"\x04role\x18\x06 \x01(\x0e2\x18.ru.rabtra.api.RoleProtoR\x04role\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x87\x01\n" +
	"\x17CreateHouseRequestProto\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x04 \x01(\tR\vhouseNumber\"8\n" +
	"\x17GetMyHousesRequestProto\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\"q\n" +
	" SearchHouseByAddressRequestProto\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x03 \x01(\tR\vhouseNumber\"\x92\x01\n" +
	"\x12HouseResponseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x03R\tcompanyId\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x05 \x01(\tR\vhouseNumber\"S\n" +
	"\x16HouseListResponseProto\x129\n" +
	"\x06houses\x18\x01 \x03(\v2!.ru.rabtra.api.HouseResponseProtoR\x06houses\"1\n" +
	"\x14GetFlatsRequestProto\x12\x19\n" +
	"\bhouse_id\x18\x01 \x01(\x03R\ahouseId\"\x93\x01\n" +
	"\x11FlatResponseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x04 \x01(\tR\vhouseNumber\x12\x1f\n" +
	"\vflat_number\x18\x05 \x01(\x05R\n" +
	"flatNumber\"O\n" +
	"\x15FlatListResponseProto\x126\n" +
	"\x05flats\x18\x01 \x03(\v2 .ru.rabtra.api.FlatResponseProtoR\x05flats\"y\n" +
	"\x18CreateMyFlatRequestProto\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x19\n" +
	"\bhouse_id\x18\x02 \x01(\x03R\ahouseId\x12\x1f\n" +
	"\vflat_number\x18\x03 \x01(\x05R\n" +
	"flatNumber\";\n" +
	"\x16GetMyFlatsRequestProto\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\"o\n" +
	"\x15UserFlatResponseProto\x12 \n" +
	"\fuser_flat_id\x18\x01 \x01(\x03R\n" +
	"userFlatId\x124\n" +
	"\x04flat\x18\x02 \x01(\v2 .ru.rabtra.api.FlatResponseProtoR\x04flat\"\\\n" +
	"\x19UserFlatListResponseProto\x12?\n" +
	"\bmy_flats\x18\x01 \x03(\v2$.ru.rabtra.api.UserFlatResponseProtoR\amyFlats\"\xcf\x01\n" +
	"\x19CreateServiceRequestProto\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\"\n" +
	"\ruser_flats_id\x18\x02 \x01(\x03R\vuserFlatsId\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.ru.rabtra.api.RequestTypeProtoR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\">\n" +
	"\x19GetMyServiceRequestsProto\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\"\x8a\x01\n" +
	"\x1eGetCompanyServiceRequestsProto\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2!.ru.rabtra.api.RequestStatusProtoH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x9a\x01\n" +
	"\x1fUpdateServiceRequestStatusProto\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.ru.rabtra.api.RequestStatusProtoR\x06status\"\x89\x05\n" +
	"\x1bServiceRequestResponseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\ruser_flats_id\x18\x02 \x01(\x03R\vuserFlatsId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\x03R\tcompanyId\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.ru.rabtra.api.RequestTypeProtoR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.ru.rabtra.api.RequestStatusProtoR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\v \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\f \x01(\tR\vhouseNumber\x12\x1f\n" +
	"\vflat_number\x18\r \x01(\x05R\n" +
	"flatNumber\x120\n" +
	"\x14applicant_first_name\x18\x0e \x01(\tR\x12applicantFirstName\x12.\n" +
	"\x13applicant_last_name\x18\x0f \x01(\tR\x11applicantLastName\x12'\n" +
	"\x0fapplicant_phone\x18\x10 \x01(\tR\x0eapplicantPhone\"i\n" +
	"\x1fServiceRequestListResponseProto\x12F\n" +
	"\brequests\x18\x01 \x03(\v2*.ru.rabtra.api.ServiceRequestResponseProtoR\brequests*B\n" +
	"\tRoleProto\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x10\n" +
	"\fROLE_COMPANY\x10\x02*\xe5\x01\n" +
	"\x10RequestTypeProto\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TYPE_DIRTY_ENTRANCE\x10\x01\x12\x18\n" +
	"\x14TYPE_ELEVATOR_BROKEN\x10\x02\x12\x18\n" +
	"\x14TYPE_NOISY_NEIGHBORS\x10\x03\x12\x11\n" +
	"\rTYPE_PLUMBING\x10\x04\x12\x14\n" +
	"\x10TYPE_ELECTRICITY\x10\x05\x12\x10\n" +
	"\fTYPE_HEATING\x10\x06\x12\x11\n" +
	"\rTYPE_INTERCOM\x10\a\x12\x10\n" +
	"\fTYPE_PARKING\x10\b\x12\x0e\n" +
	"\n" +
	"TYPE_OTHER\x10\t*e\n" +
	"\x12RequestStatusProto\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATUS_NEW\x10\x01\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x02\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x032\xb8\t\n" +
	"\tUkService\x12U\n" +
	"\n" +
	"CreateUser\x12%.ru.rabtra.api.CreateUserRequestProto\x1a .ru.rabtra.api.UserResponseProto\x12S\n" +
	"\tGetUserMe\x12$.ru.rabtra.api.GetUserMeRequestProto\x1a .ru.rabtra.api.UserResponseProto\x12X\n" +
	"\vCreateHouse\x12&.ru.rabtra.api.CreateHouseRequestProto\x1a!.ru.rabtra.api.HouseResponseProto\x12\\\n" +
	"\vGetMyHouses\x12&.ru.rabtra.api.GetMyHousesRequestProto\x1a%.ru.rabtra.api.HouseListResponseProto\x12j\n" +
	"\x14SearchHouseByAddress\x12/.ru.rabtra.api.SearchHouseByAddressRequestProto\x1a!.ru.rabtra.api.HouseResponseProto\x12\\\n" +
	"\x0fGetFlatsByHouse\x12#.ru.rabtra.api.GetFlatsRequestProto\x1a$.ru.rabtra.api.FlatListResponseProto\x12]\n" +
	"\fCreateMyFlat\x12'.ru.rabtra.api.CreateMyFlatRequestProto\x1a$.ru.rabtra.api.UserFlatResponseProto\x12]\n" +
	"\n" +
	"GetMyFlats\x12%.ru.rabtra.api.GetMyFlatsRequestProto\x1a(.ru.rabtra.api.UserFlatListResponseProto\x12l\n" +
	"\x14CreateServiceRequest\x12(.ru.rabtra.api.CreateServiceRequestProto\x1a*.ru.rabtra.api.ServiceRequestResponseProto\x12i\n" +
	"\rGetMyRequests\x12(.ru.rabtra.api.GetMyServiceRequestsProto\x1a..ru.rabtra.api.ServiceRequestListResponseProto\x12s\n" +
	"\x12GetCompanyRequests\x12-.ru.rabtra.api.GetCompanyServiceRequestsProto\x1a..ru.rabtra.api.ServiceRequestListResponseProto\x12q\n" +
	"\x13UpdateRequestStatus\x12..ru.rabtra.api.UpdateServiceRequestStatusProto\x1a*.ru.rabtra.api.ServiceRequestResponseProtoBY\n" +
	"\x12ru.rabtra.api.grpcB\x0eUkServiceProtoP\x01Z1github.com/m0dris/hackathon/internal/grpc/pb;ukpbb\x06proto3"

var (
	file_api_proto_uk_service_proto_rawDescOnce sync.Once
	file_api_proto_uk_service_proto_rawDescData []byte
)

func file_api_proto_uk_service_proto_rawDescGZIP() []byte {
	file_api_proto_uk_service_proto_rawDescOnce.Do(func() {
		file_api_proto_uk_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_uk_service_proto_rawDesc), len(file_api_proto_uk_service_proto_rawDesc)))
	})
	return file_api_proto_uk_service_proto_rawDescData
}

var file_api_proto_uk_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_uk_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_uk_service_proto_goTypes = []any{
	(RoleProto)(0),                           // 0: ru.rabtra.api.RoleProto
	(RequestTypeProto)(0),                    // 1: ru.rabtra.api.RequestTypeProto
	(RequestStatusProto)(0),                  // 2: ru.rabtra.api.RequestStatusProto
	(*CreateUserRequestProto)(nil),           // 3: ru.rabtra.api.CreateUserRequestProto
	(*GetUserMeRequestProto)(nil),            // 4: ru.rabtra.api.GetUserMeRequestProto
	(*UserResponseProto)(nil),                // 5: ru.rabtra.api.UserResponseProto
	(*CreateHouseRequestProto)(nil),          // 6: ru.rabtra.api.CreateHouseRequestProto
	(*GetMyHousesRequestProto)(nil),          // 7: ru.rabtra.api.GetMyHousesRequestProto
	(*SearchHouseByAddressRequestProto)(nil), // 8: ru.rabtra.api.SearchHouseByAddressRequestProto
	(*HouseResponseProto)(nil),               // 9: ru.rabtra.api.HouseResponseProto
	(*HouseListResponseProto)(nil),           // 10: ru.rabtra.api.HouseListResponseProto
	(*GetFlatsRequestProto)(nil),             // 11: ru.rabtra.api.GetFlatsRequestProto
	(*FlatResponseProto)(nil),                // 12: ru.rabtra.api.FlatResponseProto
	(*FlatListResponseProto)(nil),            // 13: ru.rabtra.api.FlatListResponseProto
	(*CreateMyFlatRequestProto)(nil),         // 14: ru.rabtra.api.CreateMyFlatRequestProto
	(*GetMyFlatsRequestProto)(nil),           // 15: ru.rabtra.api.GetMyFlatsRequestProto
	(*UserFlatResponseProto)(nil),            // 16: ru.rabtra.api.UserFlatResponseProto
	(*UserFlatListResponseProto)(nil),        // 17: ru.rabtra.api.UserFlatListResponseProto
	(*CreateServiceRequestProto)(nil),        // 18: ru.rabtra.api.CreateServiceRequestProto
	(*GetMyServiceRequestsProto)(nil),        // 19: ru.rabtra.api.GetMyServiceRequestsProto
	(*GetCompanyServiceRequestsProto)(nil),   // 20: ru.rabtra.api.GetCompanyServiceRequestsProto
	(*UpdateServiceRequestStatusProto)(nil),  // 21: ru.rabtra.api.UpdateServiceRequestStatusProto
	(*ServiceRequestResponseProto)(nil),      // 22: ru.rabtra.api.ServiceRequestResponseProto
	(*ServiceRequestListResponseProto)(nil),  // 23: ru.rabtra.api.ServiceRequestListResponseProto
	(*timestamppb.Timestamp)(nil),            // 24: google.protobuf.Timestamp
}
var file_api_proto_uk_service_proto_depIdxs = []int32{
	0,  // 0: ru.rabtra.api.CreateUserRequestProto.role:type_name -> ru.rabtra.api.RoleProto
	0,  // 1: ru.rabtra.api.UserResponseProto.role:type_name -> ru.rabtra.api.RoleProto
	24, // 2: ru.rabtra.api.UserResponseProto.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: ru.rabtra.api.HouseListResponseProto.houses:type_name -> ru.rabtra.api.HouseResponseProto
	12, // 4: ru.rabtra.api.FlatListResponseProto.flats:type_name -> ru.rabtra.api.FlatResponseProto
	12, // 5: ru.rabtra.api.UserFlatResponseProto.flat:type_name -> ru.rabtra.api.FlatResponseProto
	16, // 6: ru.rabtra.api.UserFlatListResponseProto.my_flats:type_name -> ru.rabtra.api.UserFlatResponseProto
	1,  // 7: ru.rabtra.api.CreateServiceRequestProto.type:type_name -> ru.rabtra.api.RequestTypeProto
	2,  // 8: ru.rabtra.api.GetCompanyServiceRequestsProto.status:type_name -> ru.rabtra.api.RequestStatusProto
	2,  // 9: ru.rabtra.api.UpdateServiceRequestStatusProto.status:type_name -> ru.rabtra.api.RequestStatusProto
	1,  // 10: ru.rabtra.api.ServiceRequestResponseProto.type:type_name -> ru.rabtra.api.RequestTypeProto
	2,  // 11: ru.rabtra.api.ServiceRequestResponseProto.status:type_name -> ru.rabtra.api.RequestStatusProto
	24, // 12: ru.rabtra.api.ServiceRequestResponseProto.created_at:type_name -> google.protobuf.Timestamp
	24, // 13: ru.rabtra.api.ServiceRequestResponseProto.updated_at:type_name -> google.protobuf.Timestamp
	22, // 14: ru.rabtra.api.ServiceRequestListResponseProto.requests:type_name -> ru.rabtra.api.ServiceRequestResponseProto
	3,  // 15: ru.rabtra.api.UkService.CreateUser:input_type -> ru.rabtra.api.CreateUserRequestProto
	4,  // 16: ru.rabtra.api.UkService.GetUserMe:input_type -> ru.rabtra.api.GetUserMeRequestProto
	6,  // 17: ru.rabtra.api.UkService.CreateHouse:input_type -> ru.rabtra.api.CreateHouseRequestProto
	7,  // 18: ru.rabtra.api.UkService.GetMyHouses:input_type -> ru.rabtra.api.GetMyHousesRequestProto
	8,  // 19: ru.rabtra.api.UkService.SearchHouseByAddress:input_type -> ru.rabtra.api.SearchHouseByAddressRequestProto
	11, // 20: ru.rabtra.api.UkService.GetFlatsByHouse:input_type -> ru.rabtra.api.GetFlatsRequestProto
	14, // 21: ru.rabtra.api.UkService.CreateMyFlat:input_type -> ru.rabtra.api.CreateMyFlatRequestProto
	15, // 22: ru.rabtra.api.UkService.GetMyFlats:input_type -> ru.rabtra.api.GetMyFlatsRequestProto
	18, // 23: ru.rabtra.api.UkService.CreateServiceRequest:input_type -> ru.rabtra.api.CreateServiceRequestProto
	19, // 24: ru.rabtra.api.UkService.GetMyRequests:input_type -> ru.rabtra.api.GetMyServiceRequestsProto
	20, // 25: ru.rabtra.api.UkService.GetCompanyRequests:input_type -> ru.rabtra.api.GetCompanyServiceRequestsProto
	21, // 26: ru.rabtra.api.UkService.UpdateRequestStatus:input_type -> ru.rabtra.api.UpdateServiceRequestStatusProto
	5,  // 27: ru.rabtra.api.UkService.CreateUser:output_type -> ru.rabtra.api.UserResponseProto
	5,  // 28: ru.rabtra.api.UkService.GetUserMe:output_type -> ru.rabtra.api.UserResponseProto
	9,  // 29: ru.rabtra.api.UkService.CreateHouse:output_type -> ru.rabtra.api.HouseResponseProto
	10, // 30: ru.rabtra.api.UkService.GetMyHouses:output_type -> ru.rabtra.api.HouseListResponseProto
	9,  // 31: ru.rabtra.api.UkService.SearchHouseByAddress:output_type -> ru.rabtra.api.HouseResponseProto
	13, // 32: ru.rabtra.api.UkService.GetFlatsByHouse:output_type -> ru.rabtra.api.FlatListResponseProto
	16, // 33: ru.rabtra.api.UkService.CreateMyFlat:output_type -> ru.rabtra.api.UserFlatResponseProto
	17, // 34: ru.rabtra.api.UkService.GetMyFlats:output_type -> ru.rabtra.api.UserFlatListResponseProto
	22, // 35: ru.rabtra.api.UkService.CreateServiceRequest:output_type -> ru.rabtra.api.ServiceRequestResponseProto
	23, // 36: ru.rabtra.api.UkService.GetMyRequests:output_type -> ru.rabtra.api.ServiceRequestListResponseProto
	23, // 37: ru.rabtra.api.UkService.GetCompanyRequests:output_type -> ru.rabtra.api.ServiceRequestListResponseProto
	22, // 38: ru.rabtra.api.UkService.UpdateRequestStatus:output_type -> ru.rabtra.api.ServiceRequestResponseProto
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_uk_service_proto_init() }
func file_api_proto_uk_service_proto_init() {
	if File_api_proto_uk_service_proto != nil {
		return
	}
	file_api_proto_uk_service_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_uk_service_proto_rawDesc), len(file_api_proto_uk_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_uk_service_proto_goTypes,
		DependencyIndexes: file_api_proto_uk_service_proto_depIdxs,
		EnumInfos:         file_api_proto_uk_service_proto_enumTypes,
		MessageInfos:      file_api_proto_uk_service_proto_msgTypes,
	}.Build()
	File_api_proto_uk_service_proto = out.File
	file_api_proto_uk_service_proto_goTypes = nil
	file_api_proto_uk_service_proto_depIdxs = nil
}
